### ISSUE TITLE
Problem with authenticator installation

### ISSUE THREAD

**Issue by Envikia** [nuxsmin/sysPass#1281]
**sysPass Version**
3.0.5

**Describe the bug**
Similar as https://github.com/sysPass/plugin-Authenticator/issues/15
May I know any solution for this problem? Thanks.

**Event log**
```
entrypoint: Starting with UID : 9001
setup_app: Setting up permissions
setup_composer_extensions: syspass/plugin-authenticator:^v2.0
~ /var/www/html
run_composer: Running composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xdebug * is missing from your system. Install or enable PHP's xdebug extension.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by andrucha97** [comment]
Same Problem here. Which command do you use?

**Comment by andrucha97** [comment]
And where is your folder?

**Comment by Envikia** [comment]
@andrucha97 , I am using docker-compose.
And here is my conf
```
    environment:
    - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.0
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/docker/appData/syspass/conf:/var/www/html/sysPass/app/config
    - /opt/docker/appData/syspass/backup:/var/www/html/sysPass/app/backup
```

**Comment by nuxsmin** [comment]
@Envikia it seems that 'require-dev' is set by default when composer is executed. I'll fix it in docker image.

Thanks for the feedback!

**Comment by fragolinux** [comment]
> @Envikia it seems that 'require-dev' is set by default when composer is executed. I'll fix it in docker image.
> 
> Thanks for the feedback!

hi, which is the correct version to use this plugin? I'm testing latest 3.1.0rc2-dev, 3.1.0rc2, 3.0.5, latest, none of them seems working... with previous version i get the xdebug extension missing, with latest 3.1.0rc2-dev i get this:

![image](https://user-images.githubusercontent.com/21192010/57620380-e46f1d00-7588-11e9-9c2e-553e052107a4.png)

**Comment by nuxsmin** [comment]
Hi @fragolinux 

you need to update the plugin version too.

Regards

**Comment by Envikia** [comment]
> 
> 
> Hi @fragolinux
> 
> you need to update the plugin version too.
> 
> Regards

Hi @nuxsmin 
May I know the correct version to use for syspass 3.0.5 ? Thanks.
I still got below log using `COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.0`
```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-xdebug * is missing from your system. Install or enable PHP's xdebug extension.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by nuxsmin** [comment]
Hi, are you running on Docker?.

If not, you need to tweak the composer arguments to not include dev packages.

Regards.

**Comment by Envikia** [comment]
HI @nuxsmin ,
Yes , I am running syspass on Docker Compose.

**Comment by nuxsmin** [comment]
Hi, sorry I didn't notice about the comments on the issue...

Hello, some tweaks have been implemented in v3.1 docker images, so xdebug extension won't be required, but this version is only compatible with plugin's v2.1.

Regards

**Comment by fragolinux** [comment]
hi, still problems... using this syspass.yml:

```
version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:3.1.0-rc4
    restart: always
    environment:
      - COMPOSER_EXTENSIONS=syspass/plugin-authenticator:^v2.1
    ports:
      - 443:443
    links:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=MYPASS
    ports:
      - 3306:3306
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}

```

i get these logs:
```
syspass-app | setup_composer_extensions: syspass/plugin-authenticator:^v2.1
syspass-app | ~ /var/www/html
syspass-app | run_composer: Running composer
syspass-app | ./composer.json has been updated
syspass-app | Loading composer repositories with package information
syspass-app | Updating dependencies
syspass-app | Your requirements could not be resolved to an installable set of packages.
syspass-app |
syspass-app |   Problem 1
syspass-app |     - The requested package syspass/plugin-authenticator ^v2.1 is satisfiable by syspass/plugin-authenticator[v2.1.x-dev] but these conflict with your requirements or minimum-stability.
syspass-app |   Problem 2
syspass-app |     - The requested PHP extension ext-xdebug * is missing from your system. Install or enable PHP's xdebug extension.
syspass-app |
syspass-app | Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
syspass-app |
syspass-app | Installation failed, reverting ./composer.json to its original content.
syspass-app | /var/www/html
syspass-app | setup_locales: Setting up locales
syspass-app | Generating locales (this might take a while)...
syspass-app |   ca_ES.UTF-8... done
syspass-app |   de_DE.UTF-8... done
syspass-app |   en_GB.UTF-8... done
syspass-app |   en_US.UTF-8... done
syspass-app |   es_ES.UTF-8... done
syspass-app |   fr_FR.UTF-8... done
syspass-app |   it_IT.UTF-8... done
syspass-app |   nl_NL.UTF-8... done
syspass-app |   pl_PL.UTF-8... done
syspass-app |   pt_BR.UTF-8... done
syspass-app |   ru_RU.UTF-8... done
syspass-app |   da.UTF-8...cannot open locale definition file `da': No such file or directory
syspass-app |  done
syspass-app |   fo.UTF-8...cannot open locale definition file `fo': No such file or directory
syspass-app |  done
syspass-app | Generation complete.
syspass-app | ######
syspass-app | sysPass environment installed and configured. Please point your browser to https://172.18.0.3 to start the installation
syspass-app | ######
syspass-app | entrypoint: Starting Apache

```
