### ISSUE TITLE
Nginx ReverseProxy Configuration

### ISSUE THREAD

**Issue by sf32738** [nuxsmin/sysPass#1386]
This is an example Nginx SSL ReverseProxy configuration that I've used in front of the docker containers.

The docker compose configuration exposes ports ```8080:80```, ```8443:443```  
From there, I have my Nginx ReverseProxy setup to point to the exposed ports.

**docker-compose.yml**
```
version: '2'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:latest
    restart: always
    networks:
      syspass:
        ipv4_address: 172.16.0.10
    ports:
      - "8080:80"
      - "8443:443"
    links:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD={{ super-secure-password }}
    networks:
      syspass:
        ipv4_address: 172.16.0.11      
    ports:
      - "3306:3306"
    volumes:
      - syspass-db:/var/lib/mysql

networks:
  syspass:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}

```

### Nginx Configuration Files
_My web server uses LetsEncrypt SSL certificates, but any valid SSL certificate authority will work._

**/etc/nginx/ssl/general_settings.conf**
```
    ssl_dhparam                 /etc/ssl/certs/dhparam.pem; ## openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
    ssl_session_timeout         10m;

    add_header                  Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
    add_header                  X-Frame-Options DENY;
    add_header                  X-Content-Type-Options nosniff;
    add_header                  X-XSS-Protection "1; mode=block";
    
    
    ssl_protocols               TLSv1.2 TLSv1.3;        # Requires nginx >= 1.13.0 else use TLSv1.2
    ssl_prefer_server_ciphers   on;
    ssl_ciphers                 'ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384';
    ssl_ecdh_curve              secp384r1;      # Requires nginx >= 1.1.0
    
    ssl_session_cache           shared:SSL:10m;
    ssl_session_tickets         off;            # Requires nginx >= 1.5.9
    ssl_stapling                on;             # Requires nginx >= 1.3.7
    ssl_stapling_verify         on;             # Requires nginx => 1.3.7

```

**/etc/nginx/sites-available/{{domain}}_80**
```
server {
    listen 80;
    return 301 https://$host$request_uri;
}
```

**/etc/nginx/sites-available/{{domain}}_443**
```
server {

  listen 443;
  server_name {{ fqdn }};

  ssl_certificate           /etc/nginx/ssl/{{ fqdn }}/fullchain.pem;
  ssl_certificate_key       /etc/nginx/ssl/{{ fqdn }}/key.pem;

  ssl on;

  ### Include SSL General Security Settings
  include ssl/general_settings.conf;

  access_log            /var/log/nginx/{{ fqdn }}_ssl_access.log;
  error_log             /var/log/nginx/{{ fqdn }}_ssl_error.log;

  location / {

    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    # Fix the “It appears that your reverse proxy set up is broken" error.
    proxy_pass          https://localhost:8443;
    proxy_read_timeout  90;

    proxy_redirect      https://localhost:8443 https://{{ fqdn }};
  }
}
```

Once you have the configurations in place, you can delete the ```default``` sites-available configuration an add these in place of it.

```
cd /etc/nginx/sites-enabled
rm -f default
ln -s /etc/nginx/sites-available/{{domain}}_80
ln -s /etc/nginx/sites-available/{{domain}}_443 
```
Once done, test your Nginx configuration and then restart the services.
```
/etc/init.d/nginx configtest
systemctl restart nginx.service
```

**Comment by orest-gulman** [comment]
This is an example with Nginx inside docker-compose:

```
version: '3'
services:
  app:
    container_name: syspass-app
    image: syspass/syspass:latest # Set this version tag to desired one
    restart: always
    expose:
      - "443"
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    # Set USE_SSL=no if you're using a LB or reverse proxy for SSL offloading
    environment:
      - USE_SSL=no
    networks:
      - syspass
    restart: unless-stopped

  db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    # Set a secure password for MariaDB root user
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    # This ports will only be accesible internally
    expose:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql
    networks:
      - syspass
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: syspass-nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./key/syspass.pem:/etc/nginx/syspass.pem:ro
     - ./key/syspass.key:/etc/nginx/syspass.key:ro
    ports:
      -  443:443
      -  80:80
    depends_on:
      - app
    networks:
      - syspass
    restart: unless-stopped

# Persistent volumes to be used across updates
volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}

networks:
  syspass:
```
