### ISSUE TITLE
302 Redirects behind Traefik

### ISSUE THREAD

**Issue by TeejMonster** [nuxsmin/sysPass#1684]
**sysPass Version**
syspass/syspass 3.1.0 (docker)
mariadb 10.2 (docker)
traefik 2.2 (docker)

**Describe the bug**
Deploying as recommended in the documentation, I am unable to reach the web interface for Syspass due to infinite 302 redirects. There are no errors in the log that 

**To Reproduce**
``` yaml
version: '2'
services:
  app:
    container_name: Syspass
    image: syspass/syspass:3.1.0
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syspass_test.rule=Host(`syspass-test.contoso.local`)"
      - "traefik.http.routers.syspass_test.entrypoints=websecure"
      - "traefik.http.routers.syspass_test.tls=true"
    ports:
      - "80"
    depends_on:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    environment:
      - USE_SSL=no
  db:
    container_name: Syspass-DB
    restart: unless-stopped
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=r3L7rkacBQTeSq8uzk2zKynr7Eg3YPyZ
    expose:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
```

**Expected behavior**
To see the Syspass web interface

**Event log**
```
entrypoint: Starting with UID : 9001,
setup_app: Setting up permissions,
setup_locales: Setting up locales,
Generating locales (this might take a while)...,
  ca_ES.UTF-8... done,
  de_DE.UTF-8... done,
  en_GB.UTF-8... done,
  en_US.UTF-8... done,
  es_ES.UTF-8... done,
  fr_FR.UTF-8... done,
  it_IT.UTF-8... done,
  nl_NL.UTF-8... done,
  pl_PL.UTF-8... done,
  pt_BR.UTF-8... done,
  ru_RU.UTF-8... done,
  da.UTF-8...cannot open locale definition file `da': No such file or directory,
 done,
  fo.UTF-8...cannot open locale definition file `fo': No such file or directory,
 done,
Generation complete.,
######,
sysPass environment installed and configured. Please point your browser to https://10.0.0.100 to start the installation,
######,
entrypoint: Starting Apache,
/usr/sbin/apache2ctl: 99: ulimit: error setting limit (Operation not permitted),
Setting ulimit failed. See README.Debian for more information.,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.0.102. Set the 'ServerName' directive globally to suppress this message,
[Sat Mar 27 18:23:01.845450 2021] [ssl:warn] [pid 712] AH01909: 10.0.0.102:443:0 server certificate does NOT include an ID which matches the server name,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.0.102. Set the 'ServerName' directive globally to suppress this message,
[Sat Mar 27 18:23:01.881655 2021] [ssl:warn] [pid 712] AH01909: 10.0.0.102:443:0 server certificate does NOT include an ID which matches the server name,
[Sat Mar 27 18:23:01.885172 2021] [mpm_prefork:notice] [pid 712] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2s configured -- resuming normal operations,
[Sat Mar 27 18:23:01.885205 2021] [core:notice] [pid 712] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND',
10.0.0.101 - - [27/Mar/2021:18:23:08 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:08 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:08 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:09 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:10 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:11 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:11 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
10.0.0.101 - - [27/Mar/2021:18:23:11 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
```

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox, Chrome, Edge
