### ISSUE TITLE
Cannot connect in https

### ISSUE THREAD

**Issue by Philippe-M** [nuxsmin/sysPass#1772]
**sysPass Version**
3.2.2 with docker

**Describe the bug**
After start the container with this docker-compose.yml

```
version: '3.3'
services:
  password:
    container_name: syspass-app
    image: syspass/syspass:3.2.2
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.password.rule=Host(`password.mydom.fr`)"
      - "traefik.http.routers.password.entrypoints=websecure"
      - "traefik.http.routers.password.tls.certresolver=le"
    links:
      - password-db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    environment:
      - USE_SSL=yes
    networks:
      - traefik
  password-db:
    container_name: syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    volumes:
      - syspass-db:/var/lib/mysql
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}
```

I've this error :

![image](https://user-images.githubusercontent.com/4558101/138727767-aef594f3-9843-4acb-924f-0c3a173a7338.png)

If I do the same test without https by setting USE_SSL = false everything works correctly

**Event log**
In the container logs I have

`syspass-app    | 172.18.0.2 - - [25/Oct/2021:15:35:24 +0000] "GET / HTTP/1.1" 302 494 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
`

**Platform (please complete the following information):**
 - OS: Linux
 - OS  Fedora
 - Browser: Firefox 93.0
